### ISSUE TITLE
How do I get at the 10 day forecast method?

### ISSUE THREAD

**Issue by bdollerup** [dknoodle/WUnderground.Net#11]
Hi there,

I can find the 10 hourly forecast and the forecast (3 days) but how do I get at the 10 day forecast?

Thanks,
Bjarne

**Comment by dknoodle** [comment]
@bdollerup - The 10 day forecast has now been added.  Most everything from the API has been added but there are still a few features not included yet.

I can't push a NuGet package update from my Mac at the moment so I will do that later this week from my PC.  In the meantime you can pull the source and should be good.  Let me know if you have any issues.

Thanks,
Daniel

**Comment by Floydan** [comment]
Getting this update to NuGet would be great!

**Comment by bdollerup** [comment]
Did you have a chance to push the update to NuGet?

**Comment by dknoodle** [comment]
NuGet version 2.0.6 published with some updates and SSL support.  Sorry it took so long!

**Comment by bdollerup** [comment]
Thanks much.... I got around the issue bu pulling the source. Thanks for getting back to me!
