### ISSUE TITLE
Hour forecast error converting week day

### ISSUE THREAD

**Issue by jjindrich** [dknoodle/WUnderground.Net#12]
Hi, I'm getting this error where downloading hour forecast with Language = 'CZ'

JsonSerializationException: Error converting value "Úterý" to type 'System.DayOfWeek'. Path 'hourly_forecast[0].FCTTIME.weekday_name', line 14, position 357.

**Comment by bdollerup** [comment]
You can get around it by making sure your locale (culture) is set to US when calling the API.

**Comment by jjindrich** [comment]
But I need to return name of Day in my local language.

**Comment by bdollerup** [comment]
If your culture is set correctly, you set the culture to "en-US" just before call the to the API and return it to you local (or default) culture after the call. You can still set the Language option to "CZ". 
Once you have the an object back from the service, you use DateTime object conversion. 
You can use
sunset.ToLocalTime() to get it to return and 
((forecastDay.Date).EpochDate).DayOfWeek to have it return the day of week according to your culture settings.

**Comment by bdollerup** [comment]
Here's how I've solved it:
```
            string _language = language;

            CultureInfo currentCulture = CultureInfo.CurrentCulture;

            CultureInfo.CurrentCulture = new CultureInfo("en-US");

            try
            {

                var _weatherforeCast = await weatherClient.GetForecastAsync(QueryType.GPS,
                    new QueryOptions() { Language = _language, Latitude = _lat.ToString(), Longitude = _lon.ToString() });
   

                CultureInfo.CurrentCulture = currentCulture;

                return _weatherforeCast;
            }
```

**Comment by dknoodle** [comment]
@jjindrich & @bdollerup - Hi Guys!

I fixed this in one place but apparently missed another.  I changed the type from DayOfWeek to string so it will handle any language.  I can't push a NuGet package update from my Mac at the moment so I will do that later this week from my PC.  In the meantime you can pull the source and should be good.  Let me know if you have any issues.

Thanks,
Daniel

**Comment by dknoodle** [comment]
NuGet version 2.0.6 published with some updates and SSL support.  Sorry it took so long!
