### ISSUE TITLE
Consider changing the base url to use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by michaelstonis** [dknoodle/WUnderground.Net#14]
All of the weather underground APIs work via HTTPS calls. It would be nice to have this as the default or to be able to change this at runtime. This is specifically an issue when using the library on a mobile platform such as iOS where calls to non-https endpoints have to be configured explicitly.

**Comment by dknoodle** [comment]
NuGet version 2.0.6 published with some updates and SSL support.  Sorry it took so long!
