### ISSUE TITLE
Any plan to support .NET Core?

### ISSUE THREAD

**Issue by TeresaP** [dknoodle/WUnderground.Net#5]
Is there any plan to support .NET Core? When I try to install with .NET Core, I get:

```Package WUnderground.Net 2.0.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package WUnderground.Net 2.0.1 supports: net45 (.NETFramework,Version=v4.5)```

**Comment by dknoodle** [comment]
Hi Teresa,

The project and NuGet package have been changed to .NetStandard so it should now work on any target framework including .Net Core.
