### ISSUE TITLE
Combining HTTP requests

### ISSUE THREAD

**Issue by rdev5** [dknoodle/WUnderground.Net#6]
Taken from their docs here (https://www.wunderground.com/weather/api/d/docs):

> Multiple API features can be combined into a single HTTP request. This is an easy way to economize your requests. The Data Features page documents how features can be combined into a single request.

Any plans to support this?

**Comment by dknoodle** [comment]
This is fully supported already.  If you look at the README.md (or main landing page for the repo) you will see examples for the Options.  Simply comma separate all the options you want to use in the method call.
