### ISSUE TITLE
Errors using the Language QueryOption

### ISSUE THREAD

**Issue by bdollerup** [dknoodle/WUnderground.Net#7]
Hi there,

I'm creating an application that I would like to be able to run in a few different languages: primarily "en-US" and "da-DK".
I've set the Language override to Danish in the OnLaunched event: 
Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = "da-DK";

And then I call your api (with the Language queryoption set to "DK"):

var Test = await client.GetForecastAsync(QueryType.GPS, new QueryOptions() { Longitude =_lon.ToString(), Latitude=_lat.ToString(), Language = "DK"});

This throws an exception with the following message:
{[type, querynotfound]}
{[description, No cities match your search query]}

Then I tried to run the call without  the Language queryoption, but with the Language override set to Danish:
var Test = await client.GetForecastAsync(QueryType.GPS, new QueryOptions() { Longitude =_lon.ToString(), Latitude=_lat.ToString()});

This still throws an exception with the following message:
{[type, querynotfound]}
{[description, No cities match your search query]}

What am I doing wrong or what did I miss?

Thanks for creating this library, regardless of my above issues, it is a lot easier that translating JSON myself!

Bjarne

**Comment by dknoodle** [comment]
Hi,

I did some testing and couldn't find an issue with this query.  If you spin up Fiddler and watch the HTTP request being generated by the library (using your sample code above) it gives me this URL:  http://api.wunderground.com/api/{your_api_key}/forecast/lang:DK/pws:True/bestfct:True/q/33.0898872,-96.8530060.json   *make sure to insert your API key into the URL

You can test the data/URL by simply putting that URL into a web browser and seeing the output.  I did notice at first I had the latitude and longitude reversed in my inputs.  When they were reversed I got the same error you did.  Check that and make sure they are in the right order.

I did see one other error come though when it was trying to convert the DayOfWeek being returned in Danish.  Oops.  I will push a NuGet update with that fix in just a bit.

**Comment by bdollerup** [comment]
I found the issue with the lon/lat. If I have the language set to "da-DK", then it converts my lon/lat to use "," as the separator instead of the correct "." as I have then as double.

**Comment by dknoodle** [comment]
Ah that makes sense!  I went back and forth several times on using Double/Decimal as the input rather than string but ultimately I found different clients had various issues with how they got their GPS data and format conversions.  I ultimately chose string for simplicity.  I'm certainly open to input or discussion on that.
