### ISSUE TITLE
Astronomy

### ISSUE THREAD

**Issue by dajanamilk** [dknoodle/WUnderground.Net#8]
I'm trying to get moonage but the value is always null. Here is how I'm doing
`
static AstronomyResponse asr1 = new AstronomyResponse();
static WeatherClient client = new WeatherClient(key);
asr1 = await client.GetAstronomyAsync(QueryType.LinkId, new QueryOptions() { LinkId = "00000.49.83671", Language = "BR" });

string moonAge = asr1.MoonPhase.AgeOfMoon;`

**Comment by dknoodle** [comment]
Hi,

This has been fixed now and a new version of the NuGet package is being indexed by NuGet now.  The issue was the data being returned from WUnderground used "moon_phase" as the property name instead of "moonPhase"
